[project]
name = "xlsxfill"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "xlsxedit>=1.0.1",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["xlsxfill", "_patched_xlsxedit"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.3",
    "ty>=0.0.72",
]
docs = [
    "mike>=2.2.0",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.7",
    "mkdocstrings[python]>=1.0.6",
]

[tool.ruff.lint]
extend-select = [
    "ANN",
    "ARG",
    "ASYNC",
    "B",
    "C4",
    "D",
    "ERA",
    "FA",
    "FBT",
    "G",
    "I",
    "LOG",
    "N",
    "PERF",
    "PIE",
    "PT",
    "PTH",
    "RET",
    "RUF",
    "S",
    "SIM",
    "TC",
    "TID",
    "UP",
    "W",
]

[tool.ruff.lint.per-file-ignores]
"tests/test_*.py" = ["S101"]

[tool.ruff.lint.pydocstyle]
convention = "google"
